const http = require('http');
const fs = require('fs');
const path = require('path');

const PORT = process.env.PORT || 3000;
const DATA_FILE = path.join(__dirname, 'fifa-pool-data.txt');
const HTML_FILE = path.join(__dirname, 'fifa-pool-shared.html');
const ESPN_SCOREBOARD_URL = 'https://site.api.espn.com/apis/site/v2/sports/soccer/fifa.world/scoreboard';
const SYNC_EVERY_MS = 5 * 60 * 1000;
const GROUP_START = new Date('2026-06-11T00:00:00Z');
const GROUP_END = new Date('2026-06-27T00:00:00Z');

const ROUNDS = [{id:'r32',matches:16},{id:'r16',matches:8},{id:'qf',matches:4},{id:'sf',matches:2},{id:'f',matches:1}];
const R32_SLOTS = [
 ['Runner-up Group A','Runner-up Group B'],['Winner Group E','Best 3rd A/B/C/D/F'],['Winner Group F','Runner-up Group C'],['Winner Group C','Runner-up Group F'],
 ['Winner Group I','Best 3rd C/D/F/G/H'],['Runner-up Group E','Runner-up Group I'],['Winner Group A','Best 3rd C/E/F/H/I'],['Winner Group L','Best 3rd E/H/I/J/K'],
 ['Winner Group D','Best 3rd B/E/F/I/J'],['Winner Group G','Best 3rd A/E/H/I/J'],['Runner-up Group K','Runner-up Group L'],['Winner Group H','Runner-up Group J'],
 ['Winner Group B','Best 3rd E/F/G/I/J'],['Winner Group J','Runner-up Group H'],['Winner Group K','Best 3rd D/E/I/J/L'],['Runner-up Group D','Runner-up Group G']
];

function defaultData(){return {pool:[],actual:{},slotMap:{},liveSync:{lastChecked:null,source:'ESPN',updatedMatches:0,groupSlotsUpdated:0,message:'Not checked yet'},updatedAt:new Date().toISOString()};}
function readData(){try{return JSON.parse(fs.readFileSync(DATA_FILE,'utf8'));}catch{const d=defaultData();writeData(d);return d;}}
function writeData(data){fs.writeFileSync(DATA_FILE,JSON.stringify(data,null,2),'utf8');}
function send(res,code,body,type='application/json'){res.writeHead(code,{'Content-Type':type,'Cache-Control':'no-store'});res.end(body);}
function collectJson(req){return new Promise((resolve,reject)=>{let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{resolve(JSON.parse(body||'{}'));}catch(e){reject(e);}});});}

function stripFlags(s){return String(s||'').replace(/[\u{1F1E6}-\u{1F1FF}]/gu,'').trim();}
function normalizeTeam(s){let x=stripFlags(s).toLowerCase().replace(/\bmen\b/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();const aliases={'usa':'united states','us':'united states','united states of america':'united states','czechia':'czech republic','korea republic':'south korea','republic of korea':'south korea','cote d ivoire':'ivory coast','côte d ivoire':'ivory coast','dr congo':'congo dr'};return aliases[x]||x;}
function sameTeam(a,b){return normalizeTeam(a)&&normalizeTeam(a)===normalizeTeam(b);}
function resolve(slot,slotMap){return slotMap?.[slot]||slot;}
function matchId(r,i){return `${ROUNDS[r].id}-${i}`;}
function getMatchTeams(data,r,i){if(r===0)return R32_SLOTS[i].map(s=>resolve(s,data.slotMap||{}));const prev=ROUNDS[r-1];return [data.actual?.[`${prev.id}-${i*2}`]||'',data.actual?.[`${prev.id}-${i*2+1}`]||''];}
function currentBracketMatches(data){const out=[];ROUNDS.forEach((round,r)=>{for(let i=0;i<round.matches;i++){const [a,b]=getMatchTeams(data,r,i);if(a&&b&&!String(a).includes('Group')&&!String(b).includes('Group')&&!String(a).includes('Best 3rd')&&!String(b).includes('Best 3rd'))out.push({id:matchId(r,i),a,b});}});return out;}
function dateRangeStrings(start,end){const out=[];for(let d=new Date(start);d<=end;d=new Date(d.getTime()+86400000))out.push(d.toISOString().slice(0,10).replace(/-/g,''));return out;}
async function fetchEspnEventsForDates(dates){const all=[];for(const date of dates){const r=await fetch(`${ESPN_SCOREBOARD_URL}?dates=${date}`);if(!r.ok)continue;const data=await r.json();all.push(...(data.events||[]));}const seen=new Set();return all.filter(e=>!seen.has(e.id)&&seen.add(e.id));}
async function fetchEspnEvents(){const dates=[];const now=new Date();for(const o of [-1,0,1])dates.push(new Date(now.getTime()+o*86400000).toISOString().slice(0,10).replace(/-/g,''));return fetchEspnEventsForDates(dates);}
function groupFromEvent(event){const comp=event?.competitions?.[0];const text=[comp?.notes?.[0]?.headline,comp?.altGameNote,event?.shortName,event?.name].filter(Boolean).join(' ');const m=String(text).match(/Group\s+([A-L])/i);return m?`Group ${m[1].toUpperCase()}`:null;}
function teamName(c){return c.team?.displayName||c.team?.shortDisplayName||c.team?.name||c.team?.abbreviation||'';}
function addStanding(groups,group,teams){groups[group]=groups[group]||{};const[a,b]=teams;if(!a.name||!b.name)return;for(const t of [a,b])groups[group][t.name]=groups[group][t.name]||{team:t.name,pts:0,gd:0,gf:0,ga:0,played:0};const A=groups[group][a.name],B=groups[group][b.name];A.played++;B.played++;A.gf+=a.score;A.ga+=b.score;A.gd+=a.score-b.score;B.gf+=b.score;B.ga+=a.score;B.gd+=b.score-a.score;if(a.score>b.score)A.pts+=3;else if(b.score>a.score)B.pts+=3;else{A.pts++;B.pts++;}}
function sortedTeams(obj){return Object.values(obj).sort((a,b)=>b.pts-a.pts||b.gd-a.gd||b.gf-a.gf||a.team.localeCompare(b.team));}
async function syncEspnGroupSlots(data){const events=await fetchEspnEventsForDates(dateRangeStrings(GROUP_START,GROUP_END));const groups={};for(const event of events){const comp=event?.competitions?.[0];if(comp?.status?.type?.completed!==true)continue;const group=groupFromEvent(event);if(!group)continue;const comps=comp?.competitors||[];if(comps.length<2)continue;const teams=comps.map(c=>({name:teamName(c),score:Number(c.score)}));if(!Number.isFinite(teams[0].score)||!Number.isFinite(teams[1].score))continue;addStanding(groups,group,teams);}data.slotMap=data.slotMap||{};let filled=0;const thirds=[];for(const [group,obj] of Object.entries(groups)){const teams=sortedTeams(obj);const completed=Object.values(obj).reduce((s,t)=>s+t.played,0)/2;if(completed>=6&&teams.length>=4){const letter=group.split(' ')[1];for(const [key,val] of [[`Winner Group ${letter}`,teams[0].team],[`Runner-up Group ${letter}`,teams[1].team]]){if(data.slotMap[key]!==val){data.slotMap[key]=val;filled++;}}thirds.push({group:letter,...teams[2]});}}
if(thirds.length===12){const ranked=thirds.sort((a,b)=>b.pts-a.pts||b.gd-a.gd||b.gf-a.gf||a.team.localeCompare(b.team));const best=new Set(ranked.slice(0,8).map(t=>t.group));const thirdMap=Object.fromEntries(ranked.slice(0,8).map(t=>[t.group,t.team]));const keys=['Best 3rd A/B/C/D/F','Best 3rd C/D/F/G/H','Best 3rd C/E/F/H/I','Best 3rd E/H/I/J/K','Best 3rd B/E/F/I/J','Best 3rd A/E/H/I/J','Best 3rd E/F/G/I/J','Best 3rd D/E/I/J/L'];for(const key of keys){const selected=key.replace('Best 3rd ','').split('/').find(g=>best.has(g));if(selected&&data.slotMap[key]!==thirdMap[selected]){data.slotMap[key]=thirdMap[selected];filled++;}}}
return {events:events.length,groupsComplete:Object.values(groups).filter(g=>Object.values(g).reduce((s,t)=>s+t.played,0)/2>=6).length,filled};}
function eventWinner(event){const comp=event?.competitions?.[0];if(comp?.status?.type?.completed!==true)return null;const comps=comp?.competitors||[];if(comps.length<2)return null;const teams=comps.map(c=>({name:teamName(c),score:Number(c.score),winner:c.winner===true}));const marked=teams.find(t=>t.winner);if(marked)return {winner:marked.name,teams:teams.map(t=>t.name)};if(Number.isFinite(teams[0].score)&&Number.isFinite(teams[1].score)&&teams[0].score!==teams[1].score)return {winner:teams[0].score>teams[1].score?teams[0].name:teams[1].name,teams:teams.map(t=>t.name)};return null;}
async function syncEspnResults(){const data=readData();let updated=0;try{const groupSync=await syncEspnGroupSlots(data);const events=await fetchEspnEvents();const bracket=currentBracketMatches(data);for(const event of events){const result=eventWinner(event);if(!result)continue;const found=bracket.find(m=>{const[x,y]=result.teams;return(sameTeam(m.a,x)&&sameTeam(m.b,y))||(sameTeam(m.a,y)&&sameTeam(m.b,x));});if(found&&!data.actual?.[found.id]){data.actual=data.actual||{};data.actual[found.id]=sameTeam(found.a,result.winner)?found.a:found.b;updated++;}}data.liveSync={lastChecked:new Date().toISOString(),source:'ESPN',updatedMatches:updated,groupSlotsUpdated:groupSync.filled,message:`Checked ${events.length} ESPN events; ${groupSync.groupsComplete}/12 groups complete; ${groupSync.filled} group slot(s) updated`};data.updatedAt=new Date().toISOString();writeData(data);console.log(data.liveSync.message);return data;}catch(e){data.liveSync={lastChecked:new Date().toISOString(),source:'ESPN',updatedMatches:0,groupSlotsUpdated:0,message:`ESPN sync failed: ${e.message}`};writeData(data);console.warn(data.liveSync.message);return data;}}

const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host}`);if(req.method==='GET'&&(url.pathname==='/'||url.pathname==='/index.html'||url.pathname==='/fifa-pool-shared.html'))return send(res,200,fs.readFileSync(HTML_FILE,'utf8'),'text/html; charset=utf-8');if(req.method==='GET'&&url.pathname==='/pool-data.txt')return send(res,200,JSON.stringify(readData(),null,2),'application/json; charset=utf-8');if(req.method==='POST'&&url.pathname==='/api/submit'){const entry=await collectJson(req);if(!entry.name||!entry.picks)return send(res,400,JSON.stringify({error:'Missing name or picks'}));const data=readData();data.pool=(data.pool||[]).filter(p=>p.name.toLowerCase()!==entry.name.toLowerCase());data.pool.push({name:entry.name,picks:entry.picks,ts:entry.ts||Date.now()});data.updatedAt=new Date().toISOString();writeData(data);return send(res,200,JSON.stringify(data));}if(req.method==='POST'&&url.pathname==='/api/state'){const incoming=await collectJson(req);const old=readData();const data={pool:incoming.pool||[],actual:incoming.actual||{},slotMap:incoming.slotMap||{},liveSync:old.liveSync||{},updatedAt:new Date().toISOString()};writeData(data);return send(res,200,JSON.stringify(data));}if(req.method==='POST'&&url.pathname==='/api/espn-sync'){const data=await syncEspnResults();return send(res,200,JSON.stringify(data));}return send(res,404,'Not found','text/plain');}catch(e){return send(res,500,JSON.stringify({error:e.message}));}});
server.listen(PORT,()=>{console.log(`FIFA pool running: http://localhost:${PORT}`);syncEspnResults();setInterval(syncEspnResults,SYNC_EVERY_MS);});
